"""Init

Revision ID: 49ff6a2ecd8d
Revises: 
Create Date: 2023-10-03 15:10:00.763760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ff6a2ecd8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('lastname', sa.String(length=36), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserRole',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserRolePermission',
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserRoleToPermission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['UserRolePermission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['UserRole.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserToRole',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['UserRole.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserSource',
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('icon_url', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ChatUser',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_source_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('platform_login', sa.String(), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_source_id'], ['UserSource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Message',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reply_user_id', sa.Integer(), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('attachment', sa.String(), nullable=True),
    sa.Column('attachment_type', sa.Enum('image', 'voice', 'geo', 'file', name='attachmenttypes'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reply_user_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ChatUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserCommentary',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ChatUser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserCommentary')
    op.drop_table('Message')
    op.drop_table('ChatUser')
    op.drop_table('UserSource')
    op.drop_table('UserToRole')
    op.drop_table('UserRoleToPermission')
    op.drop_table('UserRolePermission')
    op.drop_table('UserRole')
    op.drop_table('User')
    # ### end Alembic commands ###
