"""Remove old password field

Revision ID: 89bcf0830cf5
Revises: 9299b36250d1
Create Date: 2023-10-03 20:15:41.862718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bcf0830cf5'
down_revision: Union[str, None] = '9299b36250d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
