"""Add User fields

Revision ID: 9299b36250d1
Revises: 49ff6a2ecd8d
Create Date: 2023-10-03 20:14:35.031729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9299b36250d1'
down_revision: Union[str, None] = '49ff6a2ecd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    op.add_column('User', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('User', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('User', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_verified')
    op.drop_column('User', 'is_superuser')
    op.drop_column('User', 'is_active')
    op.drop_column('User', 'hashed_password')
    # ### end Alembic commands ###
