"""Add message_seen fiedl

Revision ID: b48dea0d89f7
Revises: f150f0e31925
Create Date: 2023-10-06 17:45:46.424898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48dea0d89f7'
down_revision: Union[str, None] = 'f150f0e31925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('message_seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'message_seen')
    # ### end Alembic commands ###
