"""Add chat_id field

Revision ID: f150f0e31925
Revises: 43b447f770ad
Create Date: 2023-10-05 18:07:07.982668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f150f0e31925'
down_revision: Union[str, None] = '43b447f770ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ChatUser', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ChatUser', 'chat_id')
    # ### end Alembic commands ###
